with-expecter: true
packages:
  github.com/darklam/gofig/interfaces:
    interfaces:
      Provider:
        config:
          filename: "mock_provider.go"
          dir: "mocks/interfaces"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "interfaces"

  github.com/darklam/gofig/providers:
    interfaces:
      VaultClienter:
        config:
          filename: "mock_vault_clienter.go"
          dir: "mocks/providers"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "providers"
